"""primeira_migracao_tabelas

Revision ID: ac587424043d
Revises: 
Create Date: 2026-01-23 22:04:50.934278

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ac587424043d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### Comandos ajustados para NÃO APAGAR nada do banco ###
    
    # 1. Ajustes na tabela movimentacoes (schema sicro)
    op.create_index(op.f('ix_sicro_movimentacoes_id'), 'movimentacoes', ['id'], unique=False, schema='sicro')
    
    # 2. Ajustes na tabela roupas (schema sicro)
    op.alter_column('roupas', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=False,
               schema='sicro')
    op.create_index(op.f('ix_sicro_roupas_id'), 'roupas', ['id'], unique=False, schema='sicro')
    
    # 3. Ajustes na tabela usuarios (schema sicro)
    op.create_index(op.f('ix_sicro_usuarios_id'), 'usuarios', ['id'], unique=False, schema='sicro')
    op.create_unique_constraint('uq_sicro_usuarios_username', 'usuarios', ['username'], schema='sicro')
    
    
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'usuarios', schema='sicro', type_='unique')
    op.drop_index(op.f('ix_sicro_usuarios_id'), table_name='usuarios', schema='sicro')
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True, schema='sicro')
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False, schema='sicro')
    op.drop_index(op.f('ix_sicro_roupas_id'), table_name='roupas', schema='sicro')
    op.create_index(op.f('ix_roupas_tipo'), 'roupas', ['tipo'], unique=False, schema='sicro')
    op.create_index(op.f('ix_roupas_id'), 'roupas', ['id'], unique=False, schema='sicro')
    op.alter_column('roupas', 'tipo',
               existing_type=sa.VARCHAR(),
               nullable=True,
               schema='sicro')
    op.drop_index(op.f('ix_sicro_movimentacoes_id'), table_name='movimentacoes', schema='sicro')
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False, schema='sicro')
    op.create_table('roupas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('tamanho', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('saldo', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('roupas_pkey'))
    )
    op.create_index(op.f('ix_roupas_tipo'), 'roupas', ['tipo'], unique=False)
    op.create_index(op.f('ix_roupas_id'), 'roupas', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), server_default=sa.text("'producao'::character varying"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey')),
    sa.UniqueConstraint('username', name=op.f('usuarios_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='gqtrack'
    )
    op.create_table('movimentacoes',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('ordem_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('usuario', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tipo', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('tamanho', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('quantidade', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('acao', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('data', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('movimentacoes_pkey'))
    )
    op.create_index(op.f('ix_movimentacoes_id'), 'movimentacoes', ['id'], unique=False)
    op.create_table('alembic_version',
    sa.Column('version_num', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('version_num', name=op.f('alembic_version_pkc'))
    )
    op.create_table('trilha_auditoria',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usuario', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('acao', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('detalhes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('trilha_auditoria_pkey')),
    schema='gqtrack'
    )
    op.create_table('materiais_estoque',
    sa.Column('codigo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('descricao', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('lote', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('status', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('validade', sa.DATE(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('lote', name=op.f('neondb_pkey')),
    schema='gqtrack'
    )
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_username'), 'usuarios', ['username'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('cellavita',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('Codigo', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Descricao', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Lote', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('Status', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('Validade', sa.DATE(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('cellavita_pkey')),
    sa.UniqueConstraint('Codigo', 'Lote', name=op.f('uq_codigo_lote'), postgresql_include=[], postgresql_nulls_not_distinct=False),
    schema='barthenderweb'
    )
    # ### end Alembic commands ###
